### ISSUE TITLE
Add Netlify redirect file

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#20]
Redirects need to go from relative to base url `https://stat545.com/` and either map onto:

- bookdown chapters that exist
- if no chapters exist, go back to original source repo published via GH Pages, so `https://STAT545-UBC.github.io/STAT545-UBC.github.io/`

Two things need to be done (https://github.com/gracelawley/practice-bookdown):

1. Add `_redirects` file to root
1. Make sure travis copies that over to the output directory

**Comment by gracelawley** [comment]
Redirect rules:
- anything that is previous `.html` and in bookdown --> redirects to bookdown
- ~anything that is previous `.md` and in bookdown --> redirects to bookdown~
- anything that is previous `.html` and not in bookdown --> redirects to ghpages
- any static image files (`.jpg`, `.png`) or data files (`.csv`, `.json`) that are not previous `.html` --> redirects to ghpages
- all else (including all `.Rmd`, `.md` files, dir folders) --> 404



Things that need to be done:
- [x] Create a csv of html files that exists at `https://stat545.com` using the `gh` package 
- [x] Create a csv of mappings for bookdown chapter headers -> original stat545 link
- [x] Create csv of netlify redirects mappings 
    - [x] Link up `https://stat545.com` links with bookdown chapters (if they exist)
    - [x] Catch any missed deprecated content and add to the appendix
- [x] Make `_redirects` file and tell travis what to do with it

Also:
- [ ] ~Create custom `404.html`~ --> #36
- [x] Add redirects for happygitwithr (see PR #34)
