### ISSUE TITLE
Rethink "Test drive R Markdown"

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#22]
This [chapter](https://stat545-book.netlify.com/r-markdown.html) is currently before the section on version control, but assumes you have done "Happy Git".

Happy Git does have this exact same content as [chapter 18](https://happygitwithr.com/rmd-test-drive.html).

Should we make the version control section more explicit, linking to specific critical/do-not-skip sections in Happy Git?

- [ ] Install Git, 

- [ ] install a Git client or GUI, 

- [ ] establish pull/push connection from computer to GitHub in the shell, 

- [ ] establish GitHub connection via RStudio,

- [ ]  credential caching, 

- [ ] troubleshooting

- [ ] Test drive R Markdown

**Comment by jennybc** [comment]
Removed. Linking out to Happy Git. Done in 6866f1743dd278ba00d3fb6d65ab2debc6df6e9f and 0c98802a92b17d45b7a7e95d5ac600b8cdfe097b.
