### ISSUE TITLE
Add + populate `admin/` folder to root

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#25]
Populate with homeworks and sample schedule from 2016 (is this most recent?) iteration:

https://github.com/gracelawley/STAT545-UBC-2016

Possibly will link in the book in Appendix A (above deprecated materials).

**Comment by gracelawley** [comment]
I started working on this ~2 weeks ago but had to stop to work on other things. I will revisit it soon but this is what I have so far:

- Script(s) that create a sample schedule based on the 2016 STAT 545 session -- the last session Jenny was the lead instructor for.
- Started working through the 2016 homeworks to see which would be easy to move over. Got through ~2-3 of them.

**Comment by jennybc** [comment]
I think we should let this go. The original stuff still lives in the old repo, if this becomes a priority. Other things seem to be have better bang for the buck.
