### ISSUE TITLE
How/where to credit whom for what

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#30]
- [ ] add RStudio Education team members who helped convert / modernize content @gracelawley @apreshill 

- [ ] @dcossyleon added CSS, new logo, and anchor linked headings (currently credited here, but may want to group differently: https://stat545-book.netlify.com/index.html#colophon)

**Comment by jennybc** [comment]
- [ ] The old People page has gone missing and needs to be resurrected / reworked.
