### ISSUE TITLE
Resolve branch cleanup-links

### ISSUE THREAD

**Issue by jennybc** [rstudio-education/stat545#41]
This branch:

https://github.com/rstudio-education/stat545/tree/cleanup-links

What is it about? I'm hoping to see:

  * Becomes a PR. After rebasing on `master` or merging `master` in.
  * Is somehow obsolete / already in here. Branch gets deleted.

**Comment by gracelawley** [comment]
This is my WIP for issue #31 -- I'm hoping to finish it up and open a PR by the end of this week.

**Comment by gracelawley** [comment]
Deleted the remote copy of this branch (kept my local copy) so I can close this issue.
