### ISSUE TITLE
Resolve branch embed-slides

### ISSUE THREAD

**Issue by jennybc** [rstudio-education/stat545#42]
This branch:

https://github.com/rstudio-education/stat545/tree/embed-slides

What is it about? I'm hoping to see:

  * Becomes a PR. After rebasing on `master` or merging `master` in.
  * Is somehow obsolete / already in here. Branch gets deleted.

**Comment by gracelawley** [comment]
I opened issue #47 for this branch and deleted the remote copy but kept my local branch.

**Comment by jennybc** [comment]
IIUC I can close this then? Correct me if I'm wrong.
