### ISSUE TITLE
Fix TOC numbering for Part II (version control and R Markdown)?

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#48]
Hey @jennybc, 

I wonder if you meant to unnumber those chapters in Part II? I think it makes sense to have the "Meta thoughts" chapter unnumbered but the other ones look a bit out of place. 

Also a side note on the CSS here: it automatically will grab the first unnumbered chapter within each part and transforms the text to upper-case, so that is why ["META THOUGHTS"](https://stat545-book.netlify.com/meta-thoughts.html) looks like that. I think it works well for when you want a part to have an overview (as you can see in ["All the Graph Things"](https://stat545-book.netlify.com/graphics-overview.html)), and thought we might want to add some in for consistency to earlier parts too at some point to frame out individual parts (since it is annoying to me that bookdown won't allow you to link to the parts themselves).

<img width="266" alt="Screen Shot 2019-09-19 at 2 14 10 PM" src="https://user-images.githubusercontent.com/12160301/65281658-f426e100-dae7-11e9-8ee2-6cbb64c2ae09.png">

If you agree aesthetically with numbering, I can offer a PR to fix.

**Comment by jennybc** [comment]
> I wonder if you meant to unnumber those chapters in section II? I think it makes sense to have the "Meta thoughts" section unnumbered but the other ones look a bit out of place.

It was intentional. But not a deeply held opinion. And after I initially created these chapters, I also reordered them, which made things weirder.

Just for vocabulary's sake, I think when you say section ... you mean "part"? In bookdown lingo. And yeah it is frustrating that you can't link to a part or easily give it a bit of front matter.

**Comment by jennybc** [comment]
So, yes, PR welcome.

**Comment by jennybc** [comment]
META THOUGHTS can probably become OVERVIEW

**Comment by apreshill** [comment]
Yes, I edited to parts for clarity above, and will do a PR.

**Comment by jennybc** [comment]
Closed in 89ad10220466113d4af4a239b8ebbc144108874d
